sudo: required

language: minimal

services:
  - docker

env:
  global:
    - DOCKER_REPO: 9jkh/codebuild-ansible
    # DOCKER_USERNAME
    - secure: "rhcy9oos9kiQxVROfI+4dmsT59v4uPEfQXG4fHWqWT3JgLlqr3ET85a3hcVfHrx4ivk66eBZyAAWpojOuBu96a5MA0wNxEerk54t+ZkXdDiNt3pAZM3ptdZhwWrn0tmzI1lB3lvxSieiVb5BbCEYWnrI/iqvxvoW8kHeWsKtkJKGW9YX59UazRN711KduP3LHSyIgFJvj9Ym1dgNwxRDzM/hgjbBXTSZcYQcICZXmbx9IPlVInUuOFmTTJkz4vIrrHk3yNecTRYa+3nxRdhp0wRdvvFR7J6573zpI1JvJI80tbbckprOaPJ4bHNGvJJ0KI5gK+rj/7AImaf4IhuetefaRAFhi567HXuDyjSn5qZpRqXOnBPlCWaqRb8TWVorDsLiS+kGRirF7ptaBND4bJwXRDKZBsqCvtXY02TiCUTGm9Ssv/52ungBDDgMjG9D421I0AhVpVnqLWb8LfgalHJJdtlA/0g9V1wWSx2zIIjIu4ptiGyrEAvrvQ0d63mVa6VCM+OJkydWN0+pAwGCUZuZfvhC+uqwQS+ib8oi9zxL1aHlqU7EvpmKrNZcGknX9kdNhhW9Z1Fj6loo6856p+wrukTIYUXItn0bez0h71tL1khgrRg2q+C11u40FrU4WyBPzsrSkLzcy2+4hocpJXmtZjvub6Er+ABh2nZ68aQ="
    # DOCKER_PASSWORD
    - secure: "nyQAS1P7mF/VfiImDEUZ233N2pQ/EfLstEnAGPkTrRSLlLIA8F3HdD/r4gB9rRCf8tMx46WRs8ntHAeEITThruzeHqi0pDveAd/tADFxca5onxf232AE6XttIRRuTAQhcyzqmLE1HQgD5ui0QURz/B4SzcqwVHE604jLTG+UhaG/q8QGDOwC8DND9/h1F6J3qhIAYxy7iAB+uHnkMEAzf/kkve9eZbJuDtw+SJEeHx+toEqu7Uh+TTCtpxY4fqAEMblJNDkEC6lDzuwGJXt0a2rEbtCZZOkC/PYIHmr+tLTi8C0inW6yGVfw/2vDpCo+5f//oEmTNkOTLcGf0jzJNP47fVDPIPHKhi/8kdieax5fYkdHtOEkQpFRry5KJA0nyqvcWdRxZyR09b0F6q2So8jEi8993q0TgnhpngemW/nKniNO2IO5rfGXkP57ZA/QAjOmo3hCsT0Jyc3tsxZYSK3lnH1WnjPrZmswQynT3NpMiOtD+QhxzYyezgqOtVg1ufFREj9qH1heJ5IkfV7NAUbWvM6dbhjBDGKHmQXKrvM6CNK1Q/CKvRgIMldj8VT1WbM4Bvet3TkBUW8nZQpIa1m7uTi8rIGFtZDzSgwFr0S1L94pTYGHVwii8iB/MAMDXxdwaS35+Q59wLaaRsY7AAlh6vFAqvyG1QGo5zkUh2w="

before_install:
  - ./build.sh

deploy:
  provider: script
  script: "./push.sh"
  skip_cleanup: true
  on:
    branch: master
