sudo: required

language: minimal

services:
  - docker

env:
  global:
    - DOCKER_REPO: 9jkh/codebuild-ansible

before_install:
  - ./build.sh

deploy:
  provider: script
  script: "./push.sh"
  skip_cleanup: true
  on:
    branch: master
